language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run build 
  - npm run lint
  - npm run style
  - npm test
after_failure:
  - "cat /home/travis/builds/Cosium/dry-dry/npm-debug.log"
