language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm run build 
  #- npm run lint
  #- npm test
  # Add more here
after_failure:
  - "cat /home/travis/builds/Cosium/dry-dry/npm-debug.log"
